# Generated by Django 2.2.8 on 2019-12-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_url', models.CharField(max_length=100)),
                ('shortened_url', models.URLField(unique=True, verbose_name='URL')),
                ('tags', models.CharField(max_length=100)),
                ('owner_username', models.CharField(max_length=32)),
            ],
        ),
    ]
