# Generated by Django 2.2.8 on 2020-01-18 07:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_url', models.CharField(max_length=100)),
                ('short_code', models.CharField(max_length=6, unique=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=1)),
                ('description', models.CharField(default='', max_length=1000)),
                ('owner_username', models.CharField(max_length=32)),
                ('usage_count', models.IntegerField(default=0)),
            ],
        ),
    ]
