# Generated by Django 2.2.8 on 2019-12-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='shortened_url',
            field=models.URLField(unique=True, verbose_name='Shortened URL'),
        ),
    ]
