# Generated by Django 2.2.8 on 2019-12-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_auto_20191213_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='shortened_url',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
