# Generated by Django 2.2.8 on 2019-12-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0003_auto_20191213_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedlink',
            name='shortened_url',
        ),
        migrations.AddField(
            model_name='shortenedlink',
            name='short_code',
            field=models.CharField(default=1, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
