# Generated by Django 2.2.8 on 2019-12-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0004_auto_20191216_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='short_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
