# Generated by Django 2.2.8 on 2019-12-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0005_auto_20191216_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedlink',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
