# Generated by Django 2.2.8 on 2020-01-15 20:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0006_shortenedlink_usage_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=10),
        ),
    ]
